# Author: Robert Feher - NetMajom Corp. - feher.robert@gmail.com

version: '3.3'

services:
  ### PHP - Apache - Xdebug ###################################################
  webserver:
    image: phpstorm/php-73-apache-xdebug-27
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    depends_on:
      - mysql
  ### MySQL ###################################################
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=dbname
    volumes:
      - ./data:/var/lib/mysql
  ### PHPMyAdmin ###############################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
  ### Composer ###################################################
  composer:
    image: composer:latest
    volumes:
      - ./:/app/
volumes:
  mysql_data: { driver: 'local' }